Bump the versions so CI works

diff --git a/nodejs/install/rwx-package.yml b/nodejs/install/rwx-package.yml
--- a/nodejs/install/rwx-package.yml
+++ b/nodejs/install/rwx-package.yml
@@ -1,27 +1,26 @@
+---
 name: nodejs/install
-version: 1.1.10
+version: 1.1.11
 description: Install Node.js, the cross-platform JavaScript runtime environment
 source_code_url: https://github.com/rwx-cloud/packages/tree/main/nodejs/install
 issue_tracker_url: https://github.com/rwx-cloud/packages/issues
-
 parameters:
   node-version:
-    description: "Version of node to install."
+    description: Version of node to install.
     required: false
   node-version-file:
-    description: "Path to node version file, eg. .node-version, .nvmrc, .tool-versions."
+    description: Path to node version file, eg. .node-version, .nvmrc, .tool-versions.
     required: false
-
 tasks:
-  - key: install
-    run: |
-      source "$RWX_PACKAGE_PATH/mint-utils.sh"
-      if ! mint_os_package_manager_in apt; then
-        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$RWX_ERRORS/error-XXXX")"
-        exit 1
-      fi
+- key: install
+  run: |
+    source "$RWX_PACKAGE_PATH/mint-utils.sh"
+    if ! mint_os_package_manager_in apt; then
+      echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$RWX_ERRORS/error-XXXX")"
+      exit 1
+    fi
 
-      $RWX_PACKAGE_PATH/bin/install-node
-    env:
-      NODE_VERSION: ${{ params.node-version }}
-      NODE_VERSION_FILE: ${{ params.node-version-file }}
+    $RWX_PACKAGE_PATH/bin/install-node
+  env:
+    NODE_VERSION: "${{ params.node-version }}"
+    NODE_VERSION_FILE: "${{ params.node-version-file }}"
