Update tests to match new behavior

diff --git a/rwx/update-packages-github/rwx-ci-cd.template.yml b/rwx/update-packages-github/rwx-ci-cd.template.yml
--- a/rwx/update-packages-github/rwx-ci-cd.template.yml
+++ b/rwx/update-packages-github/rwx-ci-cd.template.yml
@@ -1,7 +1,7 @@
 - key: gh-cli
   call: github/install-cli 1.0.1
 
-- key: update-leaves-github--test-create
+- key: test-create
   call: $LEAF_DIGEST
   with:
     repository: https://github.com/rwx-research/mint-update-leaves-testing.git
@@ -11,8 +11,8 @@
     branch-prefix: "mint-leaves-test/${{ run.id }}/"
     rwx-file: tasks.yml
 
-- key: update-leaves-github--test-create--assert
-  after: update-leaves-github--test-create
+- key: test-create--assert
+  after: test-create
   use: [gh-cli]
   run: |
     PR_NUMBER="$(gh --repo rwx-research/mint-update-leaves-testing pr list --author '@me' --label "$GITHUB_LABEL" --json number --jq 'max_by(.number) | .number')"
@@ -31,7 +31,7 @@
 
     # Check PR body
     pr_body="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json body | jq -r '.body')"
-    grep -q "Updated the following leaves" <<< "$pr_body" || { echo "Update header not found" && exit 4; }
+    grep -q "This PR was generated from" <<< "$pr_body" || { echo "Update header not found" && exit 4; }
     grep -q "mint/install-go 1.0.0 →" <<< "$pr_body" || { echo "Update mint/install-go not found" && exit 4; }
     grep -q "mint/install-node 1.0.0 →" <<< "$pr_body" || { echo "Update mint/install-node not found" && exit 4; }
 
@@ -41,13 +41,6 @@
     grep -q "+    call: mint/install-go 1." <<< "$pr_diff" || { echo "Add install-go 1.x.x not found" && exit 4; }
     grep -q "\-    call: mint/install-node 1.0.0" <<< "$pr_diff" || { echo "Delete install-node 1.0.0 not found" && exit 4; }
     grep -q "+    call: mint/install-node 1." <<< "$pr_diff" || { echo "Add install-node 1.x.x not found" && exit 4; }
-
-    # Verify no comments (until after update)
-    comment_count="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json comments | jq '.comments | length')"
-    if [ "$comment_count" != "0" ]; then
-      echo "PR #${PR_NUMBER} has $comment_count comments, expected 0"
-      exit 4
-    fi
 
     commit_count="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json commits | jq '.commits | length')"
     if [ "$commit_count" != 1 ]; then
@@ -61,58 +54,8 @@
     GITHUB_TOKEN: ${{ vaults.mint_leaves_development.github-apps.mint-mint-leaves-development.token }}
     BRANCH_PREFIX: "mint-leaves-test/${{ run.id }}/"
 
-- key: clone-test-repo
-  call: mint/git-clone 1.5.1
-  with:
-    repository: https://github.com/rwx-research/mint-update-leaves-testing.git
-    ref: main
-    preserve-git-dir: true
-    github-access-token: ${{ vaults.mint_leaves_development.github-apps.mint-mint-leaves-development.token }}
-
-- key: update-leaves-github--test--partial-revert
-  after: update-leaves-github--test-create--assert
-  use: [gh-cli, clone-test-repo]
-  run: |
-    gh --repo rwx-research/mint-update-leaves-testing pr checkout "$PR_NUMBER"
-
-    # Revert the install-go change.
-    sed -i -E "s/call: mint\/install-go\s+1.+$/call: mint\/install-go 1.0.0/" tasks.yml
-
-    if git diff --quiet; then
-      echo "Unable to make replacement for mint/install-go in tasks.yml"
-      exit 4
-    fi
-
-    git commit --all -m "Reset changes to install-go for testing."
-    git push -u origin "$(git rev-parse --abbrev-ref HEAD)"
-
-    for i in {0..15}; do
-      commit_count="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json commits | jq '.commits | length')"
-      if [ "$commit_count" -eq 2 ]; then
-        break
-      fi
-      sleep 1
-    done
-    if [ "$commit_count" != 2 ]; then
-      echo "PR #${PR_NUMBER} has $commit_count commits, expected 2"
-      exit 4
-    fi
-
-    # Ensure changes we just made have reset install-go.
-    pr_diff="$(gh --repo rwx-research/mint-update-leaves-testing pr diff "$PR_NUMBER")"
-    grep -qv "\-    call: mint/install-go 1.0.0" <<< "$pr_diff" || { echo "Found change for mint/install-go when none was expected" && exit 4; }
-    # Still have install-node changes.
-    grep -q "\-    call: mint/install-node 1.0.0" <<< "$pr_diff" || { echo "Delete install-node 1.0.0 not found" && exit 4; }
-    grep -q "+    call: mint/install-node 1." <<< "$pr_diff" || { echo "Add install-node 1.x.x not found" && exit 4; }
-
-    # Later, ensure the update doesn't reset the PR body (since it'll be a partial change).
-    gh --repo rwx-research/mint-update-leaves-testing pr edit "$PR_NUMBER" --body "Body reset for testing"
-  env:
-    GITHUB_TOKEN: ${{ vaults.mint_leaves_development.github-apps.mint-mint-leaves-development.token }}
-    PR_NUMBER: ${{ tasks.update-leaves-github--test-create--assert.values.pr-number }}
-
-- key: update-leaves-github--test-update-changes
-  after: update-leaves-github--test--partial-revert
+- key: test-update
+  after: test-create--assert
   call: $LEAF_DIGEST
   with:
     repository: https://github.com/rwx-research/mint-update-leaves-testing.git
@@ -122,86 +65,44 @@
     branch-prefix: "mint-leaves-test/${{ run.id }}/"
     rwx-file: tasks.yml
 
-- key: update-leaves-github--test-update-changes--assert
-  after: ${{ update-leaves-github--test-update-changes.succeeded && update-leaves-github--test-create--assert.succeeded }}
+- key: test-update--assert
+  after: test-update
   use: [gh-cli]
   run: |
     # PR body should not have changes.
     pr_body="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json body | jq -r '.body')"
-    grep -q "Body reset for testing" <<< "$pr_body" || { echo "PR body has not been reset for testing" && exit 4; }
 
-    for i in {0..15}; do
-      commit_count="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json commits | jq '.commits | length')"
-      if [ "$commit_count" -eq 3 ]; then
-          break
-      fi
-      sleep 1
-    done
-    if [ "$commit_count" != 3 ]; then
-      echo "PR #${PR_NUMBER} has $commit_count commits, expected 3"
-      exit 4
+    commit_count="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json commits | jq '.commits | length')"
+    if [ "$commit_count" != 1 ]; then
+      echo "PR #${PR_NUMBER} has $commit_count commits, expected 1"
+      exit 1
     fi
 
+    # Check PR body
+    pr_body="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json body | jq -r '.body')"
+    grep -q "This PR was generated from" <<< "$pr_body" || { echo "Update header not found" && exit 4; }
+    grep -q "mint/install-go 1.0.0 →" <<< "$pr_body" || { echo "Update mint/install-go not found" && exit 4; }
+    grep -q "mint/install-node 1.0.0 →" <<< "$pr_body" || { echo "Update mint/install-node not found" && exit 4; }
+
+    # Check PR diff
     pr_diff="$(gh --repo rwx-research/mint-update-leaves-testing pr diff "$PR_NUMBER")"
     grep -q "\-    call: mint/install-go 1.0.0" <<< "$pr_diff" || { echo "Delete install-go 1.0.0 not found" && exit 4; }
     grep -q "+    call: mint/install-go 1." <<< "$pr_diff" || { echo "Add install-go 1.x.x not found" && exit 4; }
     grep -q "\-    call: mint/install-node 1.0.0" <<< "$pr_diff" || { echo "Delete install-node 1.0.0 not found" && exit 4; }
     grep -q "+    call: mint/install-node 1." <<< "$pr_diff" || { echo "Add install-node 1.x.x not found" && exit 4; }
 
-    comment_count="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json comments | jq '.comments | length')"
-    if [ "$comment_count" != "1" ]; then
-      echo "PR #${PR_NUMBER} has $comment_count comments, expected 1"
-      exit 4
-    fi
-
-    # We only reset changes to install-go, so the comment shouldn't include install-node.
-    comment_body="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json comments | jq -r '.comments[0].body')"
-    grep -q "Updated the following leaves" <<< "$comment_body" || { echo "Update header not found" && exit 4; }
-    grep -q "mint/install-go 1.0.0 →" <<< "$comment_body" || { echo "Update mint/install-go not found" && exit 4; }
-    grep -qv "mint/install-node 1.0.0 →" <<< "$comment_body" || { echo "Update mint/install-node found" && exit 4; }
-  env:
-    GITHUB_TOKEN: ${{ vaults.mint_leaves_development.github-apps.mint-mint-leaves-development.token }}
-    PR_NUMBER: ${{ tasks.update-leaves-github--test-create--assert.values.pr-number }}
-
-- key: update-leaves-github--test-update-no-changes
-  after: update-leaves-github--test-update-changes--assert
-  call: $LEAF_DIGEST
-  with:
-    repository: https://github.com/rwx-research/mint-update-leaves-testing.git
-    ref: main
-    github-access-token: ${{ vaults.mint_leaves_development.github-apps.mint-mint-leaves-development.token }}
-    label: "mint-leaves-test-${{ run.id }}"
-    branch-prefix: "mint-leaves-test/${{ run.id }}/"
-    rwx-file: tasks.yml
-
-- key: update-leaves-github--test-update-no-changes--assert
-  after: ${{ update-leaves-github--test-update-no-changes.succeeded && update-leaves-github--test-create--assert.succeeded }}
-  use: [gh-cli]
-  run: |
-    for i in {0..15}; do
-      commit_count="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json commits | jq '.commits | length')"
-      if [ "$commit_count" -eq 3 ]; then
-          break
-      fi
-      sleep 1
-    done
-    if [ "$commit_count" != 3 ]; then
-      echo "PR #${PR_NUMBER} has $commit_count commits, expected 3"
-      exit 4
-    fi
-
-    comment_count="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json comments | jq '.comments | length')"
-    if [ "$comment_count" != "1" ]; then
-      echo "PR #${PR_NUMBER} has $comment_count comments, expected 1"
+    commit_count="$(gh --repo rwx-research/mint-update-leaves-testing pr view "$PR_NUMBER" --json commits | jq '.commits | length')"
+    if [ "$commit_count" != 1 ]; then
+      echo "PR #${PR_NUMBER} has $commit_count commits, expected 1"
       exit 4
     fi
   env:
     GITHUB_TOKEN: ${{ vaults.mint_leaves_development.github-apps.mint-mint-leaves-development.token }}
-    PR_NUMBER: ${{ tasks.update-leaves-github--test-create--assert.values.pr-number }}
+    PR_NUMBER: ${{ tasks.test-create--assert.values.pr-number }}
 
 - key: update-leaves-github--test--cleanup
   use: gh-cli
-  after: ${{ update-leaves-github--test-update-no-changes--assert.finished }}
+  after: ${{ test-update--assert.finished }}
   run: |
     PR_NUMBER="$(gh --repo rwx-research/mint-update-leaves-testing pr list --author '@me' --label "$GITHUB_LABEL" --json number --jq 'max_by(.number) | .number')"
     if [ -n "$PR_NUMBER" ]; then
